[package]
name = "bingus-blog"
version = "0.1.0"
edition = "2021"
default-run = "bingus-blog"

[features]
default = []
tokio-console = ["dep:console-subscriber"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = true

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
axum = { version = "0.7.5", features = ["macros"] }
bitcode = { version = "0.6.0", features = ["serde"] }
chrono = { version = "0.4.37", features = ["serde"] }
color-eyre = "0.6.3"
comrak = { version = "0.22.0", features = ["syntect"] }
console-subscriber = { version = "0.2.0", optional = true }
fronma = "0.2.0"
notify = "6.1.1"
scc = { version = "2.1.0", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
syntect = "5.2.0"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = "0.7.10"
toml = "0.8.12"
tower-http = { version = "0.5.2", features = [
  "compression-gzip",
  "fs",
  "trace",
], default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
zstd = "0.13.1"
