[package]
name = "silly-blog"
version = "0.1.0"
edition = "2021"
default-run = "silly-blog"

[[bin]]
name = "syntect-to-css"
required-features = ["clap"]

[features]
default = ["precompression"]
tokio-console = ["dep:console-subscriber"]
clap = ["dep:clap"]
precompression = ["dep:async-compression"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
strip = true

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
async-compression = { version = "0.4.8", optional = true }
axum = { version = "0.7.5", features = ["macros"] }
bitcode = { version = "0.6.0", features = ["serde"] }
chrono = { version = "0.4.37", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive"], optional = true }
color-eyre = "0.6.3"
comrak = { version = "0.22.0", features = ["syntect"] }
console-subscriber = { version = "0.2.0", optional = true }
fronma = { version = "0.2.0", features = ["toml"] }
futures-util = "0.3.30"
notify = "6.1.1"
scc = "2.1.0"
serde = { version = "1.0.197", features = ["derive"] }
syntect = "5.2.0"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
tokio-util = "0.7.10"
toml = "0.8.12"
tower-http = { version = "0.5.2", features = [
  "compression-gzip",
  "fs",
  "trace",
], default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
